steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myimage', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myimage']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['run', 'deploy', 'myfirstrun', '--image', 'gcr.io/$PROJECT_ID/myimage', '--region', 'us-central1', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/myimage
