---
- name: print hello
  hosts: webserver
  tasks:
    - name: httpd
      yum:
        name: httpd
        state: present
    - name: started
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html
---
